import { readFile, writeFile, readdir, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';
import { bundleWorker } from './worker-bundle.mjs';

const root = fileURLToPath(new URL('../extension/', import.meta.url));
await writeFile(path.join(root, 'lib/fflate.js'), '// Vendored fflate 0.8.3 (MIT); generated by tools/build.mjs.\n' +
  await readFile(new URL('../node_modules/fflate/umd/index.js', import.meta.url), 'utf8'));
await writeFile(path.join(root, 'lib/fflate-LICENSE.txt'), await readFile(new URL('../node_modules/fflate/LICENSE', import.meta.url), 'utf8'));
await writeFile(path.join(root, 'lib/opencc.js'), '// Vendored opencc-js 1.4.2; generated by tools/build.mjs.\n' +
  await readFile(new URL('../node_modules/opencc-js/dist/umd/full.js', import.meta.url), 'utf8'));
for (const [from, to] of [['LICENSE', 'opencc-LICENSE.txt'], ['THIRD_PARTY_LICENSES.md', 'opencc-THIRD-PARTY.txt'], ['LICENSES/Apache-2.0.txt', 'opencc-APACHE.txt']])
  await writeFile(path.join(root, 'lib', to), await readFile(new URL(`../node_modules/opencc-js/${from}`, import.meta.url), 'utf8'));
const sources = ['lib/settings-schema.js', 'lib/protocol.js'];
const bundle = '// GENERATED by tools/build.mjs. Edit the source modules instead.\n' +
  (await Promise.all(sources.map(async p => `// ${p}\n${await readFile(path.join(root, p), 'utf8')}`))).join('\n');
await writeFile(path.join(root, 'lib/iso-bundle.js'), bundle);
await writeFile(path.join(root, 'background-worker.js'), await bundleWorker(
  await readFile(path.join(root, 'background.js'), 'utf8'),
  p => readFile(path.join(root, p), 'utf8')));
const manifest = JSON.parse(await readFile(path.join(root, 'manifest.json'), 'utf8'));
if (manifest.key || manifest.update_url) throw new Error('Private build must have an independent extension identity.');
for (const p of [
  manifest.background.service_worker, manifest.action.default_popup, manifest.options_page,
  'work.html', 'work.js', 'work.css', 'lib/work-profiles.js', 'lib/work-lookup.js', 'work-lookup-ui.js', 'lib/work-organizer.js',
  'lib/translation-review.js', 'work-review-ui.js',
  'subtitles.html', 'subtitles.js', 'subtitles.css', 'lib/assrt.js', 'lib/subdl.js', 'lib/jimaku.js', 'lib/fflate.js', 'lib/fflate-LICENSE.txt', 'lib/collection-match.js', 'lib/external-cache.js', 'lib/external-subs.js', 'lib/episode-metadata.js',
  'lib/opencc.js', 'lib/search-names.js', 'lib/subtitle-assist.js', 'subtitle-assist-ui.js',
  ...manifest.content_scripts.flatMap(s => s.js),
  ...manifest.web_accessible_resources.flatMap(r => r.resources),
]) await access(path.join(root, p));
async function check(dir) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (e.isDirectory()) await check(path.join(dir, e.name));
    else if (e.name.endsWith('.js')) new vm.Script(await readFile(path.join(dir, e.name), 'utf8'), { filename: e.name });
  }
}
await check(root);
console.log('Bundle generated; manifest resources and JavaScript syntax verified.');
